name: ahds_assessment
channels:
  - defaults
  - conda-forge
dependencies:
  - r-essentials
  - r-tidyverse
  - r-tidytext
  - r-snowballc
  - r-readr
  - r-stringr
  - r-dplyr
  - r-lubridate
  - r-ggplot2

